# Generated by Django 4.1.3 on 2022-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='automata_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='computer_science',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='english_proficiency_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internship_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='logical_reasoning_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='quantitative_score',
            field=models.FloatField(null=True),
        ),
    ]
